remote_theme: "mmistakes/minimal-mistakes@4.24.0"
# theme: jekyll-theme-minimal
title: "Dr. Megan E. Williams"
logo: pichicuy_image.jpg
description: "Assistant Professor, Joint Appointment: Hydraulic & Environmental Engineering and Biological Sciences, Catholic University of Chile"

navbar-links:
#  About Me: "aboutme"
#  Resources:
#    - Beautiful Jekyll: "http://deanattali.com/beautiful-jekyll/"
#    - Learn markdown: "http://www.markdowntutorial.com/"
  University website: "http://obrasciviles.usm.cl/academicos/megan-williams/"
  Google scholar: "https://scholar.google.co.uk/citations?user=oNUFjE4AAAAJ"
