theme: jekyll-theme-minimal
title: "Dr. Megan E. Williams"
logo: /assets/img/logo.png
description: "Research website: Coastal processes research at the Universidad Técnica Federico Santa María"

navbar-links:
#  About Me: "aboutme"
#  Resources:
#    - Beautiful Jekyll: "http://deanattali.com/beautiful-jekyll/"
#    - Learn markdown: "http://www.markdowntutorial.com/"
  University website: "http://obrasciviles.usm.cl/academicos/megan-williams/"
  Google scholar: "https://scholar.google.co.uk/citations?user=oNUFjE4AAAAJ"
